#!/usr/bin/env python
#
# file: schemas/scripts/generate_models.py
#
# revision history:
#  20260615 (am): restyled to project conventions (no logic change)
#
# Compiles the JSON schemas in schemas/v1.0/ into the generated Pydantic
# models in hilbertbench/models/v1_0/. The output is always overwritten;
# the generated files are never edited by hand (INV-003).
#
# The script runs a sequence of pre- and post-generation checks: working
# directory, tool availability, schema presence, JSON validity,
# cross-file $ref resolution, output structure, an import smoke test,
# enum values, and a model_json_schema() roundtrip. Any failure exits
# with a non-zero code.
#
#   python schemas/scripts/generate_models.py
#
# Requires: pip install 'datamodel-code-generator[ruff]' 'pydantic>=2.6.0'
# See INV-003: docs/reference/invariants.md
#------------------------------------------------------------------------------

# future imports must come first
#
from __future__ import annotations

# import system modules
#
import importlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

#------------------------------------------------------------------------------
#
# global variables are listed here
#
#------------------------------------------------------------------------------

# set the filename using basename
#
__FILE__ = os.path.basename(__file__)

# schema input and generated-model output directories
#
SCHEMA_DIR = Path("schemas/v1.0")
OUTPUT_DIR = Path("hilbertbench/models/v1_0")
REPO_ROOT = Path(__file__).resolve().parents[2]

# the schema files that must be present, and the modules they produce
#
REQUIRED_SCHEMAS = [
    "trace.json", "span.json", "artifact.json", "catalog.json",
]
EXPECTED_MODULES = [
    "trace.py", "span.py", "artifact.py", "catalog.py",
]

# header injected at the top of every generated model file
#
FILE_HEADER = "\n".join([
    "# AUTO-GENERATED BY datamodel-codegen - DO NOT EDIT MANUALLY",
    "# Source: schemas/v1.0/",
    "# Regenerate: python schemas/scripts/generate_models.py",
    "# INV-003: Manual edits will be overwritten. Change the schema, "
    "not this file.",
])

# (module, enum name, expected values) tuples verified after generation
#
ENUM_CHECKS = [
    ("trace", "Status",
     ["SEALED_SUCCESS", "SEALED_WITH_ERRORS", "CRASHED_IN_FLIGHT",
      "INITIALIZATION_FAILED"]),
    ("trace", "Mode", ["passive", "active"]),
    ("artifact", "Kind",
     ["circuit_qasm", "pulse_schedule", "execution_outcome",
      "execution_error", "calibration_snapshot", "parameters",
      "observables", "generic_blob"]),
    ("artifact", "Encoding",
     ["json", "ndjson", "parquet", "numpy_binary", "openqasm",
      "plaintext"]),
    ("artifact", "Compression", ["gzip", "zstd", "snappy"]),
    ("span", "Status",
     ["COMPLETED", "FAILED", "PARTIAL", "IN_FLIGHT"]),
]

# (module, root model class name) tuples for the import/roundtrip checks
#
ROOT_MODELS = [
    ("trace", "HilbertbenchTraceManifest"),
    ("span", "HilbertbenchSpan"),
    ("artifact", "HilbertbenchArtifactMetadata"),
    ("catalog", "HilbertbenchArtifactCatalog"),
]

#------------------------------------------------------------------------------
#
# functions are listed here
#
#------------------------------------------------------------------------------

def ok(msg: str) -> None:
    """Print a success line for one check."""
    print(f"  [ok] {msg}")
#
# end of function


def err(msg: str) -> None:
    """Print a failure line for one check (to stderr)."""
    print(f"  [error] {msg}", file=sys.stderr)
#
# end of function


def warn(msg: str) -> None:
    """Print a non-fatal warning line for one check."""
    print(f"  [warn] {msg}")
#
# end of function


def hdr(msg: str) -> None:
    """Print a blank-line-separated section header."""
    print(f"\n{msg}")
#
# end of function


def die(msg: str, code: int = 1) -> None:
    """Print an error message and exit with the given code."""
    print(f"\n[error] {msg}", file=sys.stderr)
    sys.exit(code)
#
# end of function


def check_repo_root() -> None:
    """
    function: check_repo_root

    arguments:
     none

    return:
     none

    description:
     Exits unless the script is run from the repository root, where the
     relative schema and model paths resolve.
    """

    # the schema and model directories only exist at the repo root
    #
    hdr("Checking working directory...")
    if (not Path("schemas").is_dir()
            or not Path("hilbertbench/models").is_dir()):
        die(
            "Run from repository root.\n"
            "  cd /path/to/hilbertbench && "
            "python schemas/scripts/generate_models.py"
        )
    ok("running from repo root")
#
# end of function


def check_tools() -> list[str]:
    """
    function: check_tools

    arguments:
     none

    return:
     a list of extra datamodel-codegen formatter flags (empty when ruff
     is not installed)

    description:
     Exits if datamodel-codegen is missing; adds the ruff-format flags
     when ruff is available so the generated output is formatted.
    """

    # datamodel-codegen is mandatory
    #
    hdr("Checking required tools...")
    if not shutil.which("datamodel-codegen"):
        die(
            "datamodel-codegen not found.\n"
            "  pip install 'datamodel-code-generator[ruff]' "
            "'pydantic>=2.6.0'"
        )
    ok("datamodel-codegen found")

    # ruff is optional; when present, request formatted output
    #
    formatters: list[str] = []
    if shutil.which("ruff"):
        ok("ruff found; output will be formatted")
        formatters = ["--formatters", "ruff-format"]
    else:
        warn(
            "ruff not found; install with: "
            "pip install 'datamodel-code-generator[ruff]'"
        )

    # exit gracefully
    #
    return formatters
#
# end of function


def check_schema_files() -> None:
    """
    function: check_schema_files

    arguments:
     none

    return:
     none

    description:
     Exits if any of the required schema files is missing.
    """

    # every required schema must be present
    #
    hdr("Checking schema files...")
    for name in REQUIRED_SCHEMAS:
        path = SCHEMA_DIR / name
        if not path.exists():
            die(f"Missing schema: {path}")
        ok(name)
#
# end of function


def validate_json_and_draft() -> None:
    """
    function: validate_json_and_draft

    arguments:
     none

    return:
     none

    description:
     Parses each schema and confirms it declares JSON Schema
     draft/2020-12. Collects all problems, then exits if any were found.
    """

    # parse each schema and check its declared draft version
    #
    hdr("Validating JSON syntax and schema draft...")
    errors: list[str] = []
    for path in sorted(SCHEMA_DIR.glob("*.json")):
        try:
            data = json.loads(path.read_text())
            draft = data.get("$schema", "unknown")
            if "draft/2020-12" not in draft:
                errors.append(
                    f"{path.name}: expected draft/2020-12, got: {draft}"
                )
            else:
                ok(f"{path.name} (draft/2020-12)")
        except json.JSONDecodeError as exc:
            errors.append(f"{path.name}: {exc}")

    # report and exit on any failure
    #
    if errors:
        for e in errors:
            err(e)
        die("Schema validation failed.")
#
# end of function


def check_cross_refs() -> None:
    """
    function: check_cross_refs

    arguments:
     none

    return:
     none

    description:
     Confirms catalog.json references artifact.json (via the
     additionalProperties $ref) and that the target schema exists, so
     generation will not break on an unresolved reference.
    """

    # locate the catalog -> artifact $ref
    #
    hdr("Checking cross-file $ref resolution...")
    catalog = json.loads((SCHEMA_DIR / "catalog.json").read_text())
    additional_props = (
        catalog.get("properties", {})
               .get("artifacts", {})
               .get("additionalProperties", {})
    )

    # confirm the reference is present and resolvable
    #
    ref = additional_props.get("$ref", "")
    if "artifact.json" in ref:
        ok(f"catalog.json -> artifact.json $ref found ({ref})")
        if (SCHEMA_DIR / "artifact.json").exists():
            ok("artifact.json exists; $ref is resolvable")
        else:
            die("artifact.json not found; $ref will break generation")
    else:
        warn(
            "No $ref to artifact.json in catalog.json; "
            "verify schema structure"
        )
#
# end of function


def clean_output() -> None:
    """
    function: clean_output

    arguments:
     none

    return:
     none

    description:
     Removes and recreates the output directory so stale generated
     modules cannot survive a regeneration.
    """

    # recreate the output directory from scratch
    #
    hdr(f"Removing old {OUTPUT_DIR}/...")
    shutil.rmtree(OUTPUT_DIR, ignore_errors=True)
    OUTPUT_DIR.mkdir(parents=True)
    ok(f"{OUTPUT_DIR}/ recreated")
#
# end of function


def run_codegen(formatters: list[str]) -> None:
    """
    function: run_codegen

    arguments:
     formatters: extra datamodel-codegen formatter flags from check_tools

    return:
     none

    description:
     Invokes datamodel-codegen to compile the schemas into Pydantic v2
     models, then exits if the tool returns a non-zero code.
    """

    # build and run the datamodel-codegen command
    #
    hdr("Generating Pydantic v2 models...")
    cmd = [
        "datamodel-codegen",
        "--input", str(SCHEMA_DIR),
        "--input-file-type", "jsonschema",
        "--output", str(OUTPUT_DIR),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--target-python-version", "3.10",
        "--use-standard-collections",
        "--use-union-operator",
        "--strict-nullable",
        "--field-constraints",
        "--use-annotated",
        "--use-field-description",
        "--use-double-quotes",
        "--disable-timestamp",
        "--reuse-model",
        "--custom-file-header", FILE_HEADER,
        *formatters,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)

    # surface the tool output and exit on failure
    #
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        die("datamodel-codegen failed.")
    ok("codegen completed")
#
# end of function


def ensure_init() -> None:
    """
    function: ensure_init

    arguments:
     none

    return:
     none

    description:
     Writes a package __init__.py into the output directory if the
     generator did not create one.
    """

    # create the package marker if it is missing
    #
    init = OUTPUT_DIR / "__init__.py"
    if not init.exists():
        init.write_text("# AUTO-GENERATED PACKAGE - DO NOT EDIT\n")
        ok(f"created {init}")
#
# end of function


def verify_output_files() -> None:
    """
    function: verify_output_files

    arguments:
     none

    return:
     none

    description:
     Confirms every expected module was generated; exits listing the
     directory contents if any are missing.
    """

    # confirm each expected module is present
    #
    hdr("Checking output structure...")
    missing: list[str] = []
    for name in EXPECTED_MODULES:
        path = OUTPUT_DIR / name
        if path.exists():
            lines = path.read_text().count("\n")
            ok(f"{name} ({lines} lines)")
        else:
            err(f"{name}: NOT FOUND")
            missing.append(name)

    # report and exit on any missing module
    #
    if missing:
        print(f"\n  Generated files were: {list(OUTPUT_DIR.iterdir())}")
        die("Expected output files are missing.")
#
# end of function


def _ensure_repo_on_path() -> None:
    """Insert the repository root at the front of sys.path for imports."""
    repo = str(REPO_ROOT)
    if repo not in sys.path:
        sys.path.insert(0, repo)
#
# end of function


def smoke_test_imports() -> None:
    """
    function: smoke_test_imports

    arguments:
     none

    return:
     none

    description:
     Imports each generated module and confirms its root model class is
     present, collecting failures and exiting if any module fails.
    """

    # import each generated module and look for its root class
    #
    hdr("Smoke testing package imports...")
    _ensure_repo_on_path()
    errors: list[str] = []

    for mod_name, expected_cls in ROOT_MODELS:
        full_mod = f"hilbertbench.models.v1_0.{mod_name}"
        try:
            mod = importlib.import_module(full_mod)
            all_classes = [
                x for x in dir(mod)
                if not x.startswith("_")
                and isinstance(getattr(mod, x), type)
            ]
            needle = expected_cls.lower().replace("_", "")
            matched = [
                c for c in all_classes
                if needle in c.lower().replace("_", "")
            ]
            if matched:
                ok(f"{mod_name}.py -> {matched[0]}")
            else:
                warn(
                    f"{mod_name}.py imported OK but {expected_cls} not "
                    f"found; available: {all_classes}"
                )
        except Exception as exc:
            errors.append(f"{mod_name}.py: {exc}")

    # report and exit on any import failure
    #
    if errors:
        for e in errors:
            err(e)
        die("Import smoke test failed.")
#
# end of function


def verify_enums() -> None:
    """
    function: verify_enums

    arguments:
     none

    return:
     none

    description:
     Confirms every generated enum contains the values its schema
     declares; exits if any expected value is missing.
    """

    # compare each generated enum against its expected values
    #
    hdr("Verifying enum values against schemas...")
    _ensure_repo_on_path()
    all_ok = True

    for mod_name, enum_name, expected in ENUM_CHECKS:
        mod = importlib.import_module(
            f"hilbertbench.models.v1_0.{mod_name}"
        )
        cls = getattr(mod, enum_name, None)
        if cls is None:
            warn(f"{mod_name}.{enum_name}: not found; skipping")
            continue
        actual = [e.value for e in cls]
        missing = [v for v in expected if v not in actual]
        if missing:
            err(f"{mod_name}.{enum_name}: missing values {missing}")
            all_ok = False
        else:
            ok(
                f"{mod_name}.{enum_name}: all {len(expected)} values "
                "present"
            )

    # exit on any enum mismatch
    #
    if not all_ok:
        die("Enum verification failed.")
#
# end of function


def verify_schema_roundtrip() -> None:
    """
    function: verify_schema_roundtrip

    arguments:
     none

    return:
     none

    description:
     Calls model_json_schema() on each root model to confirm the
     generated classes are well-formed Pydantic models.
    """

    # exercise model_json_schema() on each root model
    #
    hdr("Checking model_json_schema() roundtrip...")
    _ensure_repo_on_path()

    for mod_name, cls_name in ROOT_MODELS:
        mod = importlib.import_module(
            f"hilbertbench.models.v1_0.{mod_name}"
        )
        needle = cls_name.lower().replace("_", "")
        cls = next(
            (
                getattr(mod, x)
                for x in dir(mod)
                if needle in x.lower().replace("_", "")
                and isinstance(getattr(mod, x), type)
                and hasattr(getattr(mod, x), "model_json_schema")
            ),
            None,
        )
        if cls is None:
            warn(f"{cls_name} not found in {mod_name}.py; skipping")
            continue
        schema = cls.model_json_schema()
        assert "properties" in schema or "title" in schema, (
            f"{cls_name}: empty schema"
        )
        ok(f"{cls.__name__}.model_json_schema() OK")
#
# end of function


def main() -> None:
    """
    function: main

    arguments:
     none

    return:
     none

    description:
     Runs the full check-generate-verify pipeline in order, then prints
     the follow-up steps for the developer.
    """

    # run the pipeline in order; any step exits on failure
    #
    check_repo_root()
    formatters = check_tools()
    check_schema_files()
    validate_json_and_draft()
    check_cross_refs()
    clean_output()
    run_codegen(formatters)
    ensure_init()
    verify_output_files()
    smoke_test_imports()
    verify_enums()
    verify_schema_roundtrip()

    # report success and the manual follow-up steps
    #
    print(f"\nModels generated successfully in {OUTPUT_DIR}/")
    print()
    print("Next:")
    print("  1. Update hilbertbench/models/__init__.py with \
                re-exports if needed")
    print("  2. Run: pytest tests/compliance/test_schema_roundtrip.py")
#
# end of function


# begin gracefully
#
if __name__ == "__main__":
    main()
#
# end of file
